name: 📖 Build HTML create artifact for review
on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Checking out the code 🛒
      with:
        fetch-depth: 1
    - name: Set up Python 3.10 🐍
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies 👨‍👩‍👦
      run: |
          python -m pip install --upgrade pip
          pip install -r REQUIREMENTS.txt
    - name: Build sphinx website 🏗
      run: |
          make html
    - name: Upload build artifact 📦
      uses: actions/upload-artifact@v3
      with:
        name: HTML build
        path: output
